In [1]:
import pandas as pd

In [8]:
symbol = 'ETHUSDT'
filename = f'../backtest/backtrader_integration/logs/OPT-best_results_aroon_2.pckl'
# filename = f'../backtest/backtrader_integration/logs/df_klines_{symbol}_1d.pckl'

In [9]:
df = pd.read_pickle(filename)

In [10]:
df

                           pnl_net  won  lost  trades  moneydown_max  \
BTCUSDT 240m BEST_5  8    4.351694    2     0       2      10.536115
                     14   4.351694    2     0       2      10.536115
                     20   4.351694    2     0       2      10.536115
                     26   4.351694    2     0       2      10.536115
                     32   4.351694    2     0       2      10.536115
BTCUSDT 240m WORSE_3 5  -20.417321    0     4       4      21.532423
                     11 -20.417321    0     4       4      21.532423
                     17 -20.417321    0     4       4      21.532423

                         long_won  long_lost  short_won  short_lost  \
BTCUSDT 240m BEST_5  8          2          0          0           0
                     14         2          0          0           0
                     20         2          0          0           0
                     26         2          0          0           0
                     32         2          0          0           0
BTCUSDT 240m WORSE_3 5          0          0          0           4
                     11         0          0          0           4
                     17         0          0          0           4

                         longs_pnl  shorts_pnl  leverage_factor  \
BTCUSDT 240m BEST_5  8    4.351694    0.000000              1.0
                     14   4.351694    0.000000              1.0
                     20   4.351694    0.000000              1.0
                     26   4.351694    0.000000              1.0
                     32   4.351694    0.000000              1.0
BTCUSDT 240m WORSE_3 5    0.000000  -20.417321              1.0
                     11   0.000000  -20.417321              1.0
                     17   0.000000  -20.417321              1.0

                         aroon_timeperiod  ema
BTCUSDT 240m BEST_5  8                 70   60
                     14                70   70
                     20                70   80
                     26                70   90
                     32                70  100
BTCUSDT 240m WORSE_3 5                100   50
                     11               100   60
                     17               100   70